### ISSUE TITLE
Idle-Shutdown

### ISSUE THREAD

**Issue by tomboxmeme** [teradici/cloud_deployment_scripts#203] opened 2022-12-22 17:27 UTC
Hi Hi,

Looks like this has been moved/deleted;

`"https://raw.githubusercontent.com/teradici/deploy/master/remote-workstations/new-agent-vm/Install-Idle-Shutdown.sh" -O /tmp/idleShutdown/Install-Idle-Shutdown-raw.sh`

How are you dealing with idle shutdown at the moment? I see idle logoff function but nothing to shutdown.

**Comment by shermanyin** [comment] 2022-12-22 18:59
I'll get the authors of that repo to comment. In this repo, we do have the option to install idleshutdown, see https://github.com/HPInc/cloud_deployment_scripts/blob/master/modules/gcp/centos-gfx/centos-gfx-provisioning.sh.tmpl#L301 with some explanation here: https://github.com/HPInc/cloud_deployment_scripts/tree/master/docs/gcp#workstation-idleshutdown

**Comment by shermanyin** [comment] 2022-12-22 19:47
We just realized what the problem is – the “deploy” github repo was mistakenly made private. It has just been made public again.  Sorry about the problems caused.

**Comment by shermanyin** [comment] 2023-05-23 21:56
Closing staled / fixed issue.

**Closed as completed by shermanyin** 2023-05-23 21:56 UTC
